"""init

Revision ID: cff27a089222
Revises: 
Create Date: 2024-05-14 17:58:22.261440

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cff27a089222'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account',
    sa.Column('user_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('is_email_verified', sa.Boolean(), server_default='f', nullable=False),
    sa.Column('email_verification_token', sa.String(), nullable=True),
    sa.Column('reset_password_token', sa.String(), nullable=True),
    sa.Column('date_joined', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_login_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_account_date_joined'), 'account', ['date_joined'], unique=False)
    op.create_index(op.f('ix_account_user_id'), 'account', ['user_id'], unique=False)
    op.create_index(op.f('ix_account_username'), 'account', ['username'], unique=True)
    op.create_index('username_case_sensitive_index', 'account', [sa.text('upper(username)')], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('username_case_sensitive_index', table_name='account')
    op.drop_index(op.f('ix_account_username'), table_name='account')
    op.drop_index(op.f('ix_account_user_id'), table_name='account')
    op.drop_index(op.f('ix_account_date_joined'), table_name='account')
    op.drop_table('account')
    # ### end Alembic commands ###
